# Generated by Django 5.1.4 on 2026-04-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(default='android', max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('clinic_owner', 'Clinic Owner / Primary Physician'), ('visiting_consultant', 'Visiting Consultant / Specialist')], max_length=30)),
                ('medical_council', models.CharField(choices=[('nmc', 'National Medical Commission (NMC)'), ('dci', 'Dental Council of India (DCI)'), ('inc', 'Indian Nursing Council (INC)'), ('mci_legacy', 'MCI (legacy registration)'), ('ap_mc', 'Andhra Pradesh Medical Council'), ('assam_mc', 'Assam Medical Council'), ('bihar_mc', 'Bihar Medical Council'), ('cg_mc', 'Chhattisgarh Medical Council'), ('delhi_mc', 'Delhi Medical Council'), ('goa_mc', 'Goa Medical Council'), ('gujarat_mc', 'Gujarat Medical Council'), ('hp_mc', 'Himachal Pradesh Medical Council'), ('jharkhand_mc', 'Jharkhand Medical Council'), ('karnataka_mc', 'Karnataka Medical Council'), ('kerala_mc', 'Kerala Medical Council'), ('mp_mc', 'Madhya Pradesh Medical Council'), ('maharashtra_mc', 'Maharashtra Medical Council'), ('manipur_mc', 'Manipur Medical Council'), ('odisha_mc', 'Odisha Medical Council'), ('punjab_mc', 'Punjab Medical Council'), ('rajasthan_mc', 'Rajasthan Medical Council'), ('tn_mc', 'Tamil Nadu Medical Council'), ('telangana_mc', 'Telangana Medical Council'), ('up_mc', 'Uttar Pradesh Medical Council'), ('uttarakhand_mc', 'Uttarakhand Medical Council'), ('wb_mc', 'West Bengal Medical Council'), ('other_council', 'Other / State Council')], max_length=30)),
                ('license_number', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('general_physician', 'General Physician'), ('dentist', 'Dentist'), ('oral_surgeon', 'Oral Surgeon'), ('endodontist', 'Endodontist (Root Canal Specialist)'), ('orthodontist', 'Orthodontist'), ('periodontist', 'Periodontist'), ('prosthodontist', 'Prosthodontist'), ('pedodontist', 'Pedodontist (Child Dental)'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('gynaecologist', 'Gynaecologist / Obstetrician'), ('orthopaedic', 'Orthopaedic Surgeon'), ('paediatrician', 'Paediatrician'), ('ent_specialist', 'ENT Specialist'), ('physiotherapist', 'Physiotherapist'), ('neurologist', 'Neurologist'), ('psychiatrist', 'Psychiatrist'), ('ophthalmologist', 'Ophthalmologist'), ('urologist', 'Urologist'), ('gastroenterologist', 'Gastroenterologist'), ('pulmonologist', 'Pulmonologist'), ('endocrinologist', 'Endocrinologist'), ('oncologist', 'Oncologist'), ('nephrologist', 'Nephrologist'), ('rheumatologist', 'Rheumatologist'), ('radiologist', 'Radiologist'), ('pathologist', 'Pathologist'), ('anaesthesiologist', 'Anaesthesiologist'), ('general_surgeon', 'General Surgeon'), ('plastic_surgeon', 'Plastic Surgeon'), ('neurosurgeon', 'Neurosurgeon'), ('hematologist', 'Hematologist'), ('infectious_disease', 'Infectious Disease'), ('geriatric', 'Geriatric Medicine'), ('emergency_medicine', 'Emergency Medicine'), ('other', 'Other')], max_length=50)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('about', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('degree_doc', models.FileField(blank=True, null=True, upload_to='degrees/')),
                ('clinic_proof_doc', models.FileField(blank=True, null=True, upload_to='clinic_proofs/')),
                ('is_admin_verified', models.BooleanField(default=False)),
                ('is_active_listing', models.BooleanField(default=True)),
                ('verification_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_professionals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Chandigarh', 'Chandigarh')], max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('landline_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_set_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
