# Generated by Django 5.1.4 on 2026-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpdeliverylog_medicalprofessional_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='location_locked',
            field=models.BooleanField(default=False),
        ),
    ]
