# Generated by Django 5.1.4 on 2026-05-01 18:20

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    Mp = apps.get_model('accounts', 'MedicalProfessional')
    for prof in Mp.objects.all():
        if not prof.roles and prof.role:
            prof.roles = [prof.role]
            prof.save(update_fields=['roles'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinic_location_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='role',
            field=models.CharField(choices=[('clinic_owner', 'Clinic Owner / Primary Physician'), ('hospital_owner', 'Hospital Owner / Director'), ('visiting_consultant', 'Visiting Consultant / Specialist'), ('associate_doctor', 'Associate Doctor (Short-term Coverage)')], max_length=30),
        ),
        migrations.RunPython(backfill_roles, reverse_noop),
    ]
