# Generated by Django 5.1.4 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medicalprofessional_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='primary_role',
            field=models.CharField(blank=True, choices=[('clinic_owner', 'Clinic Owner / Primary Physician'), ('hospital_owner', 'Hospital Owner / Director'), ('visiting_consultant', 'Visiting Consultant / Specialist'), ('associate_doctor', 'Associate Doctor (Short-term Coverage)'), ('academic_teaching', 'Academic / Teaching (Dental College Faculty)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='role',
            field=models.CharField(choices=[('clinic_owner', 'Clinic Owner / Primary Physician'), ('hospital_owner', 'Hospital Owner / Director'), ('visiting_consultant', 'Visiting Consultant / Specialist'), ('associate_doctor', 'Associate Doctor (Short-term Coverage)'), ('academic_teaching', 'Academic / Teaching (Dental College Faculty)')], max_length=30),
        ),
    ]
