# Generated by Django 5.1.4 on 2026-04-30 03:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clinic_lat_lng_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dental_chairs', 'Dental Chairs & Units'), ('imaging', 'Imaging & Radiology'), ('surgical_instruments', 'Surgical Instruments'), ('diagnostic', 'Diagnostic Equipment'), ('sterilization', 'Sterilization & Hygiene'), ('lab_equipment', 'Lab Equipment'), ('consumables', 'Consumables & Supplies'), ('other', 'Other')], max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open — Accepting Members'), ('funded', 'Funded — Procurement Underway'), ('active', 'Active — In Use'), ('closed', 'Closed')], default='open', max_length=10)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_created', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dental_chairs', 'Dental Chairs & Units'), ('imaging', 'Imaging & Radiology'), ('surgical_instruments', 'Surgical Instruments'), ('diagnostic', 'Diagnostic Equipment'), ('sterilization', 'Sterilization & Hygiene'), ('lab_equipment', 'Lab Equipment'), ('consumables', 'Consumables & Supplies'), ('other', 'Other')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('removed', 'Removed')], default='active', max_length=10)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to='accounts.medicalprofessional')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='equipment.marketplacelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolUsageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_slots', to='accounts.medicalprofessional')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='equipment.equipmentpool')),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='accounts.medicalprofessional')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='equipment.equipmentpool')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('pool', 'member')},
            },
        ),
    ]
