# Generated by Django 5.1.4 on 2026-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpool',
            name='purpose',
            field=models.CharField(choices=[('bulk_buy', 'Bulk Discount Buy'), ('shared_use', 'Shared Use')], default='bulk_buy', max_length=12),
        ),
    ]
