# Generated by Django 5.1.4 on 2026-05-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medicalprofessional_roles_and_more'),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantavailability',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='mobility_mode',
            field=models.CharField(choices=[('mobile', 'Mobile (move during the day)'), ('stationary', 'Stationary (work from one place)')], default='mobile', max_length=12),
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='travel_radius_km',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='visibility_mode',
            field=models.CharField(choices=[('open', 'Open — visible to all matching doctors'), ('allowlist', 'Allowlist — only my approved doctors can find me')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='working_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ConsultantAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_allowlist', to='accounts.medicalprofessional')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_by_consultants', to='accounts.medicalprofessional')),
            ],
            options={
                'unique_together': {('consultant', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='ConsultantBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_blocklist', to='accounts.medicalprofessional')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_consultants', to='accounts.medicalprofessional')),
            ],
            options={
                'unique_together': {('consultant', 'doctor')},
            },
        ),
    ]
