# Generated by Django 5.1.4 on 2026-04-30 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clinic_lat_lng_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical_emergency', 'Medical Emergency'), ('legal_issue', 'Legal Issue'), ('clinic_threat', 'Clinic Under Threat'), ('urgent_clinical', 'Urgent Clinical Assistance')], max_length=30)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.FloatField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_sent', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SosResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted / On My Way'), ('declined', 'Declined')], max_length=10)),
                ('responder_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('responder_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sos.sosalert')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['responded_at'],
                'unique_together': {('alert', 'responder')},
            },
        ),
    ]
