# Generated by Django 5.1.4 on 2026-05-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpdeliverylog_medicalprofessional_phone_verified_at_and_more'),
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sos.sosalert')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_received', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-notified_at'],
                'unique_together': {('alert', 'professional')},
            },
        ),
    ]
