# Generated by Django 5.1.4 on 2026-04-30 03:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clinic_lat_lng_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dental_lab', 'Dental Lab'), ('material_dealer', 'Dental Material Dealer'), ('equipment_technician', 'Equipment Technician / Service'), ('pharmacy', 'Pharmacy / Compounding'), ('imaging_centre', 'Imaging Centre / Radiology'), ('other', 'Other')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('avg_quality', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('avg_delivery', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_added', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-avg_rating', '-review_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraudulent or scam'), ('closed', 'Business no longer exists'), ('wrong_info', 'Incorrect information'), ('duplicate', 'Duplicate listing'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_flags', to='accounts.medicalprofessional')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to='accounts.medicalprofessional')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'reviewer')},
            },
        ),
    ]
