# Generated by Django 5.1.4 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('dental_lab', 'Dental Lab'), ('material_dealer', 'Dental Material Dealer'), ('equipment_technician', 'Equipment Technician / Service'), ('pharmacy', 'Pharmacy / Compounding'), ('imaging_centre', 'Imaging Centre / Radiology'), ('dental_assistant', 'Dental Assistant / Chairside Help'), ('other', 'Other')], max_length=25),
        ),
    ]
