# Generated by Django 5.1.4 on 2026-05-01 18:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_medicalprofessional_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_start', models.DateTimeField()),
                ('proposed_end', models.DateTimeField()),
                ('slot_kind', models.CharField(choices=[('per_slot', 'Per Slot'), ('per_day', 'Per Day')], max_length=10)),
                ('rate_quoted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('cancelled_by', models.CharField(blank=True, max_length=10)),
                ('cancel_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_bookings_received', to='accounts.medicalprofessional')),
                ('hiring_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_bookings_made', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_for_hire', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('slot_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_per_slot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('base_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('base_city', models.CharField(blank=True, max_length=100)),
                ('base_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Chandigarh', 'Chandigarh')], max_length=100)),
                ('travel_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('notes', models.TextField(blank=True, help_text='Free-form notes shown to clinics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate_profile', to='accounts.medicalprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('context', models.CharField(choices=[('associate', 'As Associate Doctor'), ('clinic', 'As Clinic Owner'), ('consultant', 'As Visiting Consultant'), ('hospital', 'As Hospital Owner'), ('general', 'General')], default='general', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_about_me', to='accounts.medicalprofessional')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_authored', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('reviewer', 'reviewee', 'context')},
            },
        ),
    ]
