# Generated by Django 5.1.4 on 2026-05-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateprofile',
            name='base_locality',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
