# Generated by Django 5.1.4 on 2026-04-30 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clinic_lat_lng_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowniePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sos_response', 'SOS Response'), ('coverage', 'Coverage / Shift Help'), ('space_lending', 'Space Lending'), ('manual', 'Manual Award')], max_length=15)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brownie_points', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('coverage', 'Patient Coverage'), ('space_lending', 'Space / Operatory Lending')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('start_dt', models.DateTimeField(blank=True, null=True)),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_requests_accepted', to='accounts.medicalprofessional')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_requests_made', to='accounts.medicalprofessional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
