# Generated by Django 5.1.4 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browniepoint',
            name='source_type',
            field=models.CharField(choices=[('sos_response', 'SOS Response'), ('coverage', 'Coverage / Shift Help'), ('space_lending', 'Space Lending'), ('find_associate', 'Found Associate'), ('manual', 'Manual Award')], max_length=15),
        ),
        migrations.AlterField(
            model_name='coveragerequest',
            name='request_type',
            field=models.CharField(choices=[('coverage', 'Patient Coverage'), ('space_lending', 'Space / Operatory Lending'), ('find_associate', 'Find Associate (Clinic Hiring)')], max_length=15),
        ),
    ]
