# Generated by Django 5.1.4 on 2026-05-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medicalprofessional_primary_role_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadreadstate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DirectMessageHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hides', to='messaging.directmessage')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_messages', to='accounts.medicalprofessional')),
            ],
            options={
                'unique_together': {('message', 'professional')},
            },
        ),
    ]
